### ISSUE TITLE
css: use Sass

### ISSUE THREAD

**Issue by takimotok** [takimotok/blog#14]
## todo

- [x] add Sass
- [x] change directory structures
- [x] consider reset.css
- [x] refine pc styles

**Comment by takimotok** [comment]
## memo

- [ ] dir. structures
- [ ] reset.css
